# Generated by Django 4.2 on 2023-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_post_publish_date_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
    ]
