# Generated by Django 4.2 on 2023-05-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_post_publish_date_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schoold_id',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
