# Generated by Django 4.2 on 2023-05-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_products_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_id',
        ),
    ]
