# Generated by Django 4.2 on 2023-05-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_feedback_post_alter_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Posts', 'posts'), ('Events', 'events'), ('Polls', 'polls')], default='Posts', max_length=10),
        ),
    ]
