# Generated by Django 4.2 on 2023-05-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_product_category_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='desc',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='product_subcategory',
        ),
    ]
