# Generated by Django 4.2 on 2023-05-06 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_cart_created_at_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 0, 4, 58, 985386)),
        ),
    ]
