# Generated by Django 4.2 on 2023-05-06 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 10, 48, 571497)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('posts', 'Posts'), ('events', 'Events'), ('news', 'News')], default='posts', max_length=10),
        ),
    ]
