# Generated by Django 4.2 on 2023-05-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_products_product_id'),
        ('main', '0041_alter_cart_created_at_alter_product_product_price'),
    ]

    operations = [
    ]
