# Generated by Django 4.2 on 2023-05-07 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_remove_order_billing_address_order_shipping_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 12, 9, 1, 862445)),
        ),
    ]
