# Generated by Django 4.2 on 2023-05-07 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_cart_created_at_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 14, 34, 43, 551260)),
        ),
    ]
