# Generated by Django 4.2.1 on 2023-05-09 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_cart_created_at_alter_order_status_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 1, 7, 53, 194132)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Posts', 'Posts'), ('Events', 'Events'), ('News', 'News')], default='posts', max_length=10),
        ),
    ]
