# Generated by Django 4.2.1 on 2023-05-09 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_cart_created_at_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 9, 3, 27, 11, 344422)),
        ),
    ]
