# Generated by Django 4.2.1 on 2023-05-10 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 13, 50, 0, 507106)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
